### ISSUE TITLE
FreeCAD GUI icon missing

### ISSUE THREAD

**Issue by Giorgio-IT** [OpenMandrivaAssociation/distribution#2780]
**OpenMandriva version**:4.3

**Describe the bug**:in FreeCAD graphic interface two icons regarding zoom are missing: Show All and Show Selection. 

**Steps to reproduce**:

**Observed behavior**:
 ![FreeCAD_OMLx](https://user-images.githubusercontent.com/747201/155720485-0c0638d4-589b-4074-a9dd-9d8be725ad9d.png)

**Expected behavior**: 
![FreeCAD19_Appimage](https://user-images.githubusercontent.com/747201/155720583-ff5851ab-e8b2-4e1b-a8ca-bab209b0ee08.png)

**Additional comment**: see also https://forum.openmandriva.org/t/freecad-wont-install/4262/21?u=giorgio
it seems that changing theme solve the problem

**Logs and screenshots if relevant**

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/freecad-wont-install/4262/29

**Comment by mandian** [comment]
bug fixed in upstream and will be in netx release of breeze icon
https://bugs.kde.org/show_bug.cgi?id=450870#c5

As a workaround the use the following code in a terminal
```
for t in breeze breeze-dark
do
	for s in 16 22 32
	do
		sudo ln -s zoom-original.svg /usr/share/icons/$t/actions/$s/zoom-all.svg 
		sudo ln -s zoom-fit-best.svg /usr/share/icons/$t/actions/$s/zoom-selection.svg
	done
done

```
Here is the result
![FreeCAD_icons](https://user-images.githubusercontent.com/18350688/163732882-2c70dfeb-308b-44da-9426-111d37996f78.png)
