### ISSUE TITLE
The package glibc-static-devel is gigantic

### ISSUE THREAD

**Issue by bogdro** [OpenMandrivaAssociation/distribution#2787]
**OpenMandriva version**: 4.3

**Describe the bug**:
The package `glibc-static-devel` is gigantic (over 2 gigabytes) when compared to the previous release and to what I'd expect.

**Steps to reproduce**:
Install (or even just download) `glibc-static-devel`. Run `rpm -qi glibc-static-devel` and check the size. Compare the result with OpenMandriva 4.2.
Alternatively, compare
http://abf-downloads.openmandriva.org/4.2/repository/x86_64/main/release/
with
http://abf-downloads.openmandriva.org/rock/repository/x86_64/main/release/

**Observed behavior**:
The package is over 2 GIGAbytes in size.

**Expected behavior**:
I suppose the package should be no more than a few MEGAbytes in size, just like it was before.

**Additional comment**:
I've tried to look over the changes made, but the volume was too big.

**Logs and screenshots if relevant**

**Comment by berolinux** [comment]
This is already fixed in cooker

$ rpm -q glibc-static-devel
glibc-static-devel-2.35-1.znver1
$ rpm -qi glibc-static-devel |grep Size
Size        : 16108708

Not sure what went wrong in 4.3 - probably the debuginfo generator failing to strip the debug info.
We may want to release cooker glibc as an update for 4.3.

**Comment by bogdro** [comment]
Thank you!
Apart from this and the inability tu update clang (missing `libomptarget.so(VERS1.0)(64bit)` and maybe something else; noted in https://github.com/OpenMandrivaAssociation/distribution/issues/2768 which is closed without a final solution for those who wish to have clang), a `dnf up` from 4.2 to 4.3 went quite smoothly. Good idea to update the grub configuration more often (huge problem when moving from 4.1 to 4.2!).
I guess the defect can be closed once cooker's glibc is moved to rock.
Keep up the good work!

**Comment by benbullard79** [comment]
The errors in #2768 are because the person posting used `dnf up` which is not the correct command to do a distribution upgrade. You need to use `dnf --refresh dsync` at a minimum. It would be perhaps even better to do `dnf clean all ; dnf dsync`.

There is more about the distribution upgrade from Lx 4.2 to 4.3 here: https://forum.openmandriva.org/t/upgrading-om-lx-4-2-system-to-om-lx-4-3/4338

**Comment by benbullard79** [comment]
Cooker is glibc-2.35 Rock/Lx 4.3 is glibc-2.34. I wonder if copying cooker glibc to Rock is possible? 

I was wondering if the glibc-2.34 could simply be rebuilt or if in needs a special fix of some kind?

**Comment by rugyada** [comment]
Solved cooker
