### ISSUE TITLE
iwd wifi does not start (Cooker)

### ISSUE THREAD

**Issue by benbullard79** [OpenMandrivaAssociation/distribution#2801]
**OpenMandriva version**:
Cooker, Rolling, not sure about 4.3.
**Describe the bug**:
With iwd enabled when I reboot wifi does not start.
**Steps to reproduce**:
Follow steps to set-up system to use iwd here: https://github.com/OpenMandrivaAssociation/distribution/issues/2712
Then reboot.
**Observed behavior**:
wifi does not start. User has to start it manually for every boot or login.
**Expected behavior**:
Normally enter wifi password on first boot and thereafter it just starts automatically.
**Additional comment**:
Issue observed on Cooker and Rolling systems on multiple computers.
**Logs and screenshots if relevant**
This journal log show when I boot in to system and wifi does not start:

[journal-iwd-wifi-not-start.txt](https://github.com/OpenMandrivaAssociation/distribution/files/8839255/journal-iwd-wifi-not-start.txt)

To start manually I only have to click on "connect". This would indicate perhaps some authentication problem or incorrect path? The log show that iwd want to start.

I *think* maybe this is relevant:
`Jun 04 21:46:30 C-F2FS-938 kernel: wlan0: aborting authentication with 88:d7:f6:e4:77:f0 by local choice (Reason: 3=DEAUTH_LEAVING)`

[omdv-bug-report-20220604221320.log](https://github.com/OpenMandrivaAssociation/distribution/files/8839264/omdv-bug-report-20220604221320.log)

Let me know what I can do to help resolve this issue.

Issue observed on 2 boxes with Qualcomm Atheros AR9485 using driver: ath9k and another box with Intel Wi-Fi 6 AX200 driver: iwlwifi.

**Comment by tpgxyz** [comment]
Hi @benbullard79 thanks for sharing your findings.
I prepared new iwd-1.28 please give it a try.
What i noticed is that our kernel is missing CONFIG_KEY_DH_OPERATIONS which means interfaces configured with WPS will not work with IWD. Anyways i commited a fix for that in our kernel.
Second our wireless-regdb were updated too.

**Comment by tpgxyz** [comment]
@benbullard79 Thanks. This means iwd works, right ?
@AngryPenguinPL  Can you run iwd test also, just to confirm it is working ?

**Comment by benbullard79** [comment]
> @benbullard79 Thanks. This means iwd works, right ? 

Yes. Both my old notebooks with Qualcomm Atheros AR9485 have proper working wifi not. And wifi starts automatically after booting and logging in.

**Comment by AngryPenguinPL** [comment]
@tpgxyz Honestly, I have been testing IWD as a daily driver on my computer for two weeks. But I am not speaking because I want to check two things first.

- On pc with cooker

I use here usb dongle TL-WN722N with ath9k_htc driver. 
From the moment the IWD is installed, the old IWD is deactivated. The IWD seems to replace the entry in the networkmanager configuration with wpa to iwd. However, to be sure, I removed the wpa completely.
IWD works, connects automatically to the default WIFI network, but from time to time, completely randomly disconnects from the WiFi and then reconnects after a second or two. This is a bit annoying, especially when you upload or download a large file, the disconnect means you have to start it again. Probably in online games it will also be disturbing. I checked the log and so far I can not see anything that would directly indicate the reason.
Seconds things is missing wifi 5ghz network. My router broadcasts two networks of 2.4 GHz and 5 GHz. By default I use 2,4 here. However, in the list of available networks after IWD installation, I only see the first one.

So quickly my thoughts. I will check if I see the same problems in the notebook as well.

**Comment by benbullard79** [comment]
I just narrowed the scope of this bug report to Cooker. 
Today and for quite a while with iwd in Cooker wifi starts automatically when one boots or reboots. However if I logout/login it does not start wifi automatically. Granted internet connection is just a mouse click away so not that big of a deal. I post this in the spirit of what users are likely to expect and that we would want this to work automatically.

**Comment by benbullard79** [comment]
[omdv-bug-report-20220630153632.log](https://github.com/OpenMandrivaAssociation/distribution/files/9023212/omdv-bug-report-20220630153632.log)

**Comment by benbullard79** [comment]
iwd in cooker restart when re-boot is fixed.
