### ISSUE TITLE
Don't link to OpenGL

### ISSUE THREAD

**Issue by davidebeatrici** [OpenMandrivaAssociation/distribution#2804]
https://github.com/OpenMandrivaAssociation/mumble/blob/c04b41b9c32bf4acd9a987be9ffe1ab5c9e3452e/mumble-1.4.0-fix-linking-failure-in-overlay_gl.patch

The OpenGL symbols should be loaded when the library is injected into the target process. This is achieved with the `-Wl,-z,lazy` linker option: https://github.com/mumble-voip/mumble/blob/414ab61b61b0d446eccba1c60dcad7c158a7c701/overlay_gl/CMakeLists.txt#L66-L69

> Linking the overlay library with '-z now' requires all target processes to have libGL symbols in them at load time.
> If it doesn't, the program will not start at all.
> 
> Instead, explicitly use '-z lazy' to defer libGL symbol resolution until first use, which is never for non-libGL users.

If compilation fails, it's probably because our linker option is overridden.

**Comment by berolinux** [comment]
This happens because of the linker flag `-Wl,--no-undefined`, which explicitly requests not allowing symbols that can't be resolved at link time. We (and presumably PCLinuxOS as well) enable this to catch errors (like trying to use a symbol that doesn't exist anymore in the current version of libraries etc).
That can be turned off (by using `%define _disable_ld_no_undefined 1` in the spec file), but does it make sense? What is the purpose of not linking to OpenGL directly? Mumble uses Qt, which in turn uses OpenGL anyway, so mumble without OpenGL isn't going to do anything useful...

**Comment by ZeroAbility** [comment]
It appears to be commented in your spec file:

https://github.com/OpenMandrivaAssociation/mumble/pull/7/commits/714d58456c590a50483e104af3cad024baa4561a#diff-05d2cb045525d9a98d27555e78d4afd4f3d7cbcbafb4cc6f32fb4c57fd9f955cR53

I do agree that safety is important. In my case, adding `lGL` or the lib  path are not working, but that is not an OpenMandriva problem.

**Comment by davidebeatrici** [comment]
@berolinux It's about the overlay library that is injected into the target process, not Mumble itself.

**Comment by AngryPenguinPL** [comment]
All right, I just dropped the GL linkage patch.
Fixed by
https://github.com/OpenMandrivaAssociation/mumble/commit/e58f3ffbbf92a33556e32dae0f12610266fdc356

Fixed package is available in the Cooker release.

**Comment by davidebeatrici** [comment]
Excellent, thank you very much!
