### ISSUE TITLE
Installation fails on installing bootloader when using f2fs

### ISSUE THREAD

**Issue by eugen-br** [OpenMandrivaAssociation/distribution#2845]
**OpenMandriva version**: OpenMandriva Lx release 4.50 (ROME) Rolling for znver1 with kernel 5.19.5-desktop-1omv4090 OpenMandrivaLx.rome-silver-candidate-plasma.znver1.iso

**Describe the bug**: When I try to install a Rolling release the installation fails at installing the bootloader.

**Steps to reproduce**: Try to install from OpenMandrivaLx.rome-silver-candidate-plasma.znver1.iso or from OpenMandrivaLx.5.0-TP-plasma.znver1.iso on Asus ROG laptop model GL702ZC on a M.2 SSD.

**Observed behavior**: An error window pops up at installing bootloader step:
The bootloader could not be installed. The installation command <pre>grub2-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=OpenMandriva_Lx_[GRUB] --force</pre> returned error code 1.

**Expected behavior**: The bootloader should get installed.

**Additional comment**: I didn't try to install a different OpenMandriva ISO of non-rolling type.
[calamares.txt](https://github.com/OpenMandrivaAssociation/distribution/files/9602456/calamares.txt)

**Logs and screenshots if relevant**
Incomplete termonal output of sudo -E calamares -d attached.

**Comment by eugen-br** [comment]
a complete Calamares log
[complete calamares log .txt](https://github.com/OpenMandrivaAssociation/distribution/files/9602659/complete.calamares.log.txt)

**Comment by benbullard79** [comment]
Thanks for reporting. I can confirm this issue is valid.

`fs: :   "f2fs"`

`[PYTHON JOB]: "Bootloader: grub (efi)"
    .. Running ("grub2-install", "--target=x86_64-efi", "--efi-directory=/boot/efi", "--bootloader-id=OpenMandriva_Lx_[GRUB]", "--force")
    .. Target cmd: ("grub2-install", "--target=x86_64-efi", "--efi-directory=/boot/efi", "--bootloader-id=OpenMandriva_Lx_[GRUB]", "--force") Exit code: 1 output:
 Installing for x86_64-efi platform.
grub2-install: error: unknown filesystem.`

Installing with f2fs does not work with recent OpenMandriva isos for Cooker and ROME.

**Comment by benbullard79** [comment]
IMO this should be a blocker because of this as shown in screen-shot:

![Screenshot_20220919_183330](https://user-images.githubusercontent.com/5704386/191137063-f41b8de6-7365-40c9-8a2d-6ff770cd2127.jpg)

Really need to either fix this or remove `f2fs` from the option window ins Calamares.

**Comment by tpgxyz** [comment]
`f2fs` was working previously

**Comment by eugen-br** [comment]
@tpgxyz /boot/efi in my first test yesterday was completely a new one. I went with manual partitioning in Calamares. I even created a new partition table. In the second test I kept the partitions but chose the "format" option.

@benbullard79 Grub2 was not installed on an f2fs partition. "Unknown filesystem" refers to th fat32 /boot/efi partition. But I can test install on a different root filesystem.

**Comment by eugen-br** [comment]
I've just successfully reinstalled.
I selected the option "replace partition" and and let the installer replace the f2fs root partition with the default ext4 one.
I'm attaching the terminal output.
[calamares replace partition worked.txt](https://github.com/OpenMandrivaAssociation/distribution/files/9610709/calamares.replace.partition.worked.txt)

**Comment by eugen-br** [comment]
Another successful test with btrfs as root filesystem.
[calamares success with btrfs root.txt](https://github.com/OpenMandrivaAssociation/distribution/files/9610885/calamares.success.with.btrfs.root.txt)

**Comment by benbullard79** [comment]
@eugen-br: I just did a test using erase disk in calamres and `f2fs` and got the same error you did. 

I had said `f2fs` believing this to be the same or similar to this previous bug: https://github.com/OpenMandrivaAssociation/distribution/issues/2777. However the error message is not exactly the same. In 2777 the error says:

`grub2-install: error: cannot find a device for /boot/grub2 (is /dev mounted?).`

Also that bug was regarding `btrfs` and `xfs` not `f2fs`. I recall that bug was something in OM `grub2` package somewhere or in  our `grub2-install` script but I am not positive of this. 

_I am not anywhere near an expert at deciphering all these logs can tell us_. Does`grub2-install` install things to both `/boot` which would be part of `/` and `/boot/efi` which as we know is a separate partition? Or does `grub2-install` read files installed in `/boot` by `grub2-mkconfig`? And would both of those be part of the same script along with `os-prober`?

**Comment by eugen-br** [comment]
I remember I tried a manual chroot and grub-install with a previous OpenMandriva Technical Preview release and it failed with f2fs as root filesystem. But I haven't reported back then in July.

@benbullard79 can you test the grub-install command?

Grub installs files into the /boot folder. If the /boot folder is on an unsupported filesystem then it can't use it. It looks like I got used to Grub version which supports f2fs. (I'm a Manjaro user.) Now I remembered that f2fs support in Grub is quite new. I read here https://wiki.archlinux.org/title/F2FS#GRUB_support and here https://wiki.archlinux.org/title/GRUB#Unsupported_file_systems

So my recommendation is for OpenMandriva to either throw an error message if /boot is on a unsupported filesystem. 
Or to patch grub2 package. (For comparison: https://gitlab.manjaro.org/manjaro-arm/packages/core/grub/-/blob/main/PKGBUILD)

**Comment by tpgxyz** [comment]
Let me clarify couple of things that was mentioned above.
1. Arch/Manjaro grub2 sources has nothing specific nor related to f2fs - yet they are updated to latest upstream git snapshot. To be honest our grub2 is somewhat patched to latest git snapshot - maybe worth to investigate to switch to full git snapshot.
2. We are talking about` /boot/efi` being set up on a different partition that `/`. So` /boot/efi` is on fat32 and grub2-install tries to install payload on that partition
3. f2fs file system was supported by OpenMandriva since 2015
4. Grub2 has official support for f2fs file system since 2018
5. There are rumours that` extra_attr` attribute added to mkfs.f2fs can cause grub2 to stop booting 
https://forum.endeavouros.com/t/installer-cant-correctly-setup-grub-when-root-is-f2fs-or-xfs/20497
https://savannah.gnu.org/bugs/?59976
https://forum.manjaro.org/t/grub-mkconfig-failed-when-i-install-21-3/114978/7

Please notice this:
```
    ..  mapping for "/dev/sda1" "/dev/sda1"
     partlabel :   "EFI"
     partition-uuid (partuuid) :   "PartUUID$4f2611cb"
     parttype :   ""
     partattrs :   "0"
     mountPoint: :   "/boot/efi"
     fs: :   "fat32"
     fsName :   "fat32"
     filesystem-uuid (uuid) :   "FSUUID$c280dc8c"
     claimed :   "true"
    ..  mapping for "/dev/sda2" "/dev/sda2"
     partlabel :   "root"
     partition-uuid (partuuid) :   "PartUUID$a3f4574e"
     parttype :   ""
     partattrs :   "0"
     mountPoint: :   "/"
     fs: :   "f2fs"
     fsName :   "f2fs"
     filesystem-uuid (uuid) :   "FSUUID$be2caf8e"
     claimed :   "true"
```

I'm happy that i'm not using grub2 for many years, and systemd-boot does what i supposed to do without issues.

**Comment by rugyada** [comment]
> 3\. f2fs file system was supported by OpenMandriva since 2015

Yep
https://arc.openmandriva.org/blog/2016/04/3244/
Officially announced, still support started long time before.

**Comment by eugen-br** [comment]
> 2\. We are talking about` /boot/efi` being set up on a different partition that `/`. So` /boot/efi` is on fat32 and grub2-install tries to install payload on that partition

I'm not 100% sure, but in the folder /boot there are folders /efi and /grub. On /boot/efi the fat32 partition is mounted. But /boot/grub resides in my test case on a f2fs partition. And I think that grub2-install or grub2-mkconfig writes into /boot/grub.

> maybe worth to investigate to switch to full git snapshot.

I would support to try that, at least on the rolling or dev branch.

**Comment by eugen-br** [comment]
I could also test an installation of the stable image on a f2fs root partition....

**Comment by tpgxyz** [comment]
I may have feeling what may be wrong here.
` .. Running ("grub2-install", "--target=x86_64-efi", "--efi-directory=/boot/efi", "--bootloader-id=OpenMandriva_Lx_[GRUB]", "--force")`
Above command wants to install grub2 on `/boot/efi`, while a real `/boot/efi` is not mounted. So `/boot/efi` comes from `/` filesystem which is `f2fs` while real `/boot/efi` comes from different partition which is `fat32`

**Comment by eugen-br** [comment]
@tpgxyz with technical preview version I tried to manually install Grub2, mounted / and /boot/efi, ran the comman grub2-install with --boot-directory=/mnt/boot and --efi-directory=/boot/efi and got the same error.

**Comment by benbullard79** [comment]
berolinux suggested a workaround so obvious that I am kicking myself for not thinking of it myself.

Use Manual Partitioning and create a seperate `/boot` partition with `ext4` fs. I tested this in VBox and it works. I am confident it will work on HW as well. He suggested to make it 256 MB. I doubled it for my test just to be safe. In my test I use a 100 MB `/boot/efi` fat32 partition, this is optional and up to user.

![Screenshot_20221019_121355](https://user-images.githubusercontent.com/5704386/196763715-69dd68ff-f591-47ce-bf71-93d0a1211ca5.jpg)

You can ignore this error message and click OK:

![Screenshot_20221019_121410](https://user-images.githubusercontent.com/5704386/196763870-e7e30c5f-a960-4043-9a03-9519e0f69c42.jpg)

Resutl:

![Screenshot_20221019_121951](https://user-images.githubusercontent.com/5704386/196763890-a435c55c-2e15-4744-8a45-7be4ace8f365.jpg)

I used ROME iso # 1403 simply because I already had it downloaded. This should work on any cooker, rome, or rock iso.

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/installing-omlx-with-f2fs/4682/2

**Comment by rugyada** [comment]
Erase disk simplified option now is set to ext4 default.
Use Manual partitioning for any other different setup.

**Comment by benbullard79** [comment]
This bug is not fixed. I tested this with ROME iso #1600 using manual partitioning. If user uses `f2fs` for / we still see this error:

![Screenshot_20230101_141742](https://user-images.githubusercontent.com/5704386/210183624-5a571513-3c51-4757-a22e-bde9c81051cb.jpg)
I believe in the logs this is the problem"

![Screenshot_20230101_141848](https://user-images.githubusercontent.com/5704386/210183633-75f00a0a-118f-4aab-a8f6-6a07ab5c8533.jpg)

[calamares-install.log](https://github.com/OpenMandrivaAssociation/distribution/files/10329403/calamares-install.log)

**Comment by benbullard79** [comment]
FWIW: The Calamares installer does create the `f2fs` partiton and install the system as we can see in this screen shot:

![Screenshot_20230101_143017](https://user-images.githubusercontent.com/5704386/210183837-a3060f8e-3a0d-41d0-beb0-45f58d2a0ea7.jpg)

Perhaps that will help point to where the issue is. Something in grub2? Not sure.

**Comment by benbullard79** [comment]
Maybe this: `/usr/bin/grub2-probe: error: unknown filesystem.`

**Comment by tpgxyz** [comment]
It turned out that this was the culprit https://git.savannah.gnu.org/cgit/grub.git/commit/?id=4bd9877f62166b7e369773ab92fe24a39f6515f8

Please try with grub2-2.06-4

**Comment by benbullard79** [comment]
I made a new Cooker x86_64 iso #1609 and it definitely has grub2 2.06-4. Installation was successful using `f2fs` for /. 

I believe this is fixed. So I wlll push the new grub2 2,06-4 to Rome main/release repos and any new isos for Cooker or ROME will have this fix. As I recall this was not broken for 4.3.

Thanks tpgxyz. This one was important to me. 

Guess I should reboot and be sure it boots.

**Comment by benbullard79** [comment]
But unfortunately there is a problem. Rather a large problem at that. The fix for f2fs works on x86_64 iso's but znver1 iso's are broken now and do not work at all.

![Screenshot_20230103_010749](https://user-images.githubusercontent.com/5704386/210289965-6c7e9a2e-e553-4606-ba76-21ffc09933b2.jpg)

[calamares-install-znver1.log](https://github.com/OpenMandrivaAssociation/distribution/files/10333959/calamares-install-znver1.log)

`ERROR: Module "bootloader" requires "partition" before it in sequence.`   >>>    but no idea why this occurs on znver1 iso's only.

FWIW: I tested 2 x86_64 iso's # 1609 & 1611 and both work and do install boot loader using f2fs. Then tested 2 znver1 isos # 1610 & 1612 and both are broken as described.

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/most-recent-rome-rolling-iso/4640/14

**Comment by benbullard79** [comment]
I have tested ROME slim and regular Plasma znver1 and x86_64 iso's and Cooker slim znver1 and x86_64 iso's. All installed with `f2fs`. I believe we can consider this bug fixed.

The ROME iso #'s are 1613, 1614, 1615, and 1616. The Cooker iso's tested are #'s 1617, and 1618.
