### ISSUE TITLE
openmandriva can't start with vmware gpu

### ISSUE THREAD

**Issue by usama-makhzoum** [OpenMandrivaAssociation/distribution#2863]
**OpenMandriva version**:
4.3 ROCKS
**Describe the bug**:
boot hangs, can't start anything inside qemu while choosing vmware as vga option
**Steps to reproduce**:
start inside qemu using `-vga vmware`
**Observed behavior**:
hang, even in recovery or console mode 
**Expected behavior**:
normal booting process
**Additional comment**:
I have the package  `libdri64-drm-vmwgfx` installed

**Comment by benbullard79** [comment]
I can boot Cooker and ROME isos in Qemu with some variation of this command:

`$ qemu-system-x86_64 -enable-kvm Path_to.iso -drive file=/Data1/QemuVMs/iso-test.img -m 2G -cpu host -smp 2 -M pc -vga virtio -display sdl,gl=on -usb -usbdevice mouse -usbdevice keyboard -audio pa,model=hda`

But there is an additional trick. Any older isos (made before # 1526) you have to boot to cli. Then remove `x11-driver-input-vmmouse`. Then startx and do what you want, install if you want.

I boot the installed system with this: 

`$ qemu-system-x86_64 -enable-kvm -drive file=/Data1/QemuVMs/iso-test.img -m 2G -cpu host -smp 2 -M pc -vga virtio -display sdl,gl=on -usb -usbdevice mouse -usbdevice keyboard -audio pa,model=hda`

I have not tried it yet but this should work with 4.3/Rock.

I don't know vmware and can not help with that. OM devs, as far as I know, won't touch vmware because of the license.

**Note:** I am not expert on Qemu, I just learned how to do this in last few days from info from [OM devs](https://wiki.openmandriva.org/en/team/chat) and [youtube video](https://github.com/OpenMandrivaAssociation/distribution/issues/2863). Knowledge wise I am a user that has been around Mandriva since 2008 and OM since it began.

**Comment by benbullard79** [comment]
I started the beginning of a how to or tutorial on this [here](https://forum.openmandriva.org/t/using-qemu-in-rome-and-cooker/4713).

**Comment by omakuta** [comment]
This issue has been mentioned on **OMA forum**. There might be relevant details there:

https://forum.openmandriva.org/t/using-qemu-in-rome-and-cooker/4713/2
