### ISSUE TITLE
Making Ungoogled-Chromium the default browser and the extensions problem resulting from it 

### ISSUE THREAD

**Issue by hakerdefo** [OpenMandrivaAssociation/distribution#2888]
ROME (Plasma Slim) ships with Ungoogled-Chromium the default browser and this is resulting in an impossibility if one wishes to add any extension to it. Going to [https://chrome.google.com/webstore](https://chrome.google.com/webstore) via the Ungoogled-Chromium browser doesn't let you install anything as `Add to Chrome` button is unavailable. Manually installing an extension via developer-mode is also no good as it is resulting in an error like this,

`Failed to unpack CRX  `

Setting-up of custom DOH provider is also resulting in an error,

`Please verify that this is a valid provider.`

Surfing the web without `uBlock Origin` or other good ad-blocking extension is a horrible experience on most websites. So, why not ship good ole Firefox as the default browser? And, if you are really bent on shipping Chromium as the default browser, then vanilla Chromium will be a better choice than Ungoogled-Chromium IMPO.

**Comment by benbullard79** [comment]
As far as Chromium. I _think_ that is because of [this.](https://blog.chromium.org/2021/01/limiting-private-api-availability-in.html) There is [this](https://www.chromium.org/developers/how-tos/api-keys/) for more information.

I do not know what vanilla Chromium is. 

_As I understand things_ OMLx Plasma ISOs are designed to be as free from G stuff as possible (gtk, ect.). That is OM developer preference. They want to keep the Plasma ISOs as close to KDE/Qt applications as possible. Thus no Firefox on the Plasma ISOs.

"So, why not ship good ole Firefox as the default browser?" We do provide a module to install Firefox in OM-Welcome. I do not know for sure if OM-Welcome is on the slim isos. At any rate it is very easy to install. So is installing Google Chrome, Microsoft Edge, or Brave. For those user just needs to add the third party repository with Software Repository Selector (`om-repo-picker`). And of course the standard "user is responsible for any 3rd party software user installs" disclaimer.

I use a combination of Falkon, Firefox, and Google Chrome, _As I understand it_ Falkon is based on Chromium code and to me it seems to work better. If user wants to use Google stuff in Chromium there does not seem to me to be any reason not to just use Chrome. Either way they have your information already.

**Comment by hakerdefo** [comment]
OM-Welcome is right there and user is absolutely able to install other browsers from it. But, an average user most likely won't be able to understand that Ungoogled-Chromium has intentionally removed support for installing extensions from the Chrome web-store as s/he might not be able to tell that the version they are using is not the standard Chromium but Ungoogled-Chromium and they will mistakenly think that something is broken.

Vanilla Chromium is the one where no components are intentionally stripped-out.

**Comment by benbullard79** [comment]
> OM-Welcome is right there and user is absolutely able to install other browsers from it. But, an average user most likely won't be able to understand that Ungoogled-Chromium has intentionally removed support for installing extensions from the Chrome web-store as s/he might not be able to tell that the version they are using is not the standard Chromium but Ungoogled-Chromium and they will mistakenly think that something is broken.
> 
> Vanilla Chromium is the one where no components are intentionally stripped-out.

_First I need to admit I do not know all about Chromium_. Where are the sources for Vanilla Chromium? I could be wrong but I thought the stripping out of Google stuff was done by Chromium because Google made them do it. For better answer you could ask OM devs about this at OpenMandriva Chat.

You can check in our [GH sources here](https://github.com/OpenMandrivaAssociation/chromium-browser-stable). It looks like our source packages for Chromium-Browser-Stable are from [here](https://gsdview.appspot.com/chromium-browser-official/). But there is also this under Source0: https://commondatastorage.googleapis.com/chromium-browser-official/. I _think_ that would be where the actual tar.xz file come from. There is also this in the .spec file: https://chromiumdash.appspot.com/releases?platform=Linux

So confusing to me... But I thought our source packages came directly from Chromium project.

**Comment by benbullard79** [comment]
Looking it does look like this is something OM is adding a patch for:

```
%if 0%{?ungoogled:1}
Source1000:	https://github.com/ungoogled-software/ungoogled-chromium/archive/%{ungoogled}.tar.gz
Patch1000:	chromium-107-fix-build-after-ungoogling.patch
%endif
```
