### ISSUE TITLE
Adding Base to LibreOffice

### ISSUE THREAD

**Issue by Ubuntu-2020** [OpenMandrivaAssociation/distribution#2898]
1. Adding to **LibreOffice** the module **Base**. Now he is missing:
 ![LibreOffice-Base](https://user-images.githubusercontent.com/65112331/232760392-71c1645e-84b1-4945-a72a-8c4b1627f4a6.gif)

2. Adding to **LibreOffice** additional icons. Now only **Breeze** icons present in LibreOffice.

**Comment by rugyada** [comment]
> 1. Adding to **LibreOffice** the module **Base**. Now he is missing:

Not "missed". Base is not in default ISO packages list by decision, because of lot of deps it would install along with it and also because usually it's not among the apps common users will need for daily use.
Nonetheless it is avaliable in repository of course

```
$ sudo dnf clean all;dnf clean all;dnf repolist
$ sudo dnf install libreoffice-base
```
![ss_20230418_134947](https://user-images.githubusercontent.com/46781309/232768756-545e4de6-625d-4509-8dde-2f32eecac4f6.jpg)
