### ISSUE TITLE
qt-creator cannot be installed 

### ISSUE THREAD

**Issue by SACViper** [OpenMandrivaAssociation/distribution#2900]
**OpenMandriva ROME**:

**qt-creator cannot be installed when trying to install problem of conflicting request libLLVM-14.so is needed**:

**sudo dnf install qt-creator**:

Error: 
 Problem: conflicting requests
  - nothing provides libLLVM-14.so()(64bit) needed by qt-creator-8.0.1-2.x86_64
  - nothing provides libLLVM-14.so(LLVM_14)(64bit) needed by qt-creator-8.0.1-2.x86_64
  - nothing provides libclang-cpp.so.14()(64bit) needed by qt-creator-8.0.1-2.x86_64
(try to add '--skip-broken' to skip uninstallable packages)

**Expected behavior**:

**Additional comment**:

**Logs and screenshots if relevant**

**Comment by benbullard79** [comment]
That would be because rolling repos have llvm 15 not 14. I am not a developer so if there is any code that needs fixing I can't do that. I did start x86_64 builds in cooker and rolling to see if the new `qt-creator` builds. Cooker has llvm 16 and rolling has llvm 15 so my guess is the rolling build *might* work and the cooker build should fail. We shall see.

If either build fails then I or you can attempt to get developers attention on [OpenMandriva Chat](https://wiki.openmandriva.org/en/team/chat). _It does help_ if the actual users of the software contact devs themselves.

**Comment by rugyada** [comment]
Is this bug report still valid?
Looks like fixed to me

![ss_20230605_102926](https://github.com/OpenMandrivaAssociation/distribution/assets/46781309/357728d9-9651-4819-9c20-c6d5073b9dc2)
