### ISSUE TITLE
Xfce 4.19

### ISSUE THREAD

**Issue by edwardp3** [OpenMandrivaAssociation/distribution#2906]
I'm on the Xfce mailing list. They have begun to release some packages with version 4.19 which are at https://archive/xfce/org/src/xfce

https://mail.xfce.org/pipermail/xfce/2023-January/subject.html
https://mail.xfce.org/pipermail/xfce/2023-March/subject.html
https://mail.xfce.org/pipermail/xfce/2023-April/subject.html

Could these be added to Cooker? I tried to input as a Pull Request, but was not able to.

Thank you.

**Comment by AngryPenguinPL** [comment]
I don't think so. 4.19 is an unstable (development) series, and we at Cooker are currently working on fine-tuning the snapshot, which will soon go to ROME and later to Lx 5.0. That's why we want to avoid unstable alpha or beta releases.

As for 4.18... it is currently updating xfce 4.18 components to their latest releases.

**Comment by edwardp3** [comment]
OK, thank you.
