### ISSUE TITLE
ROME 23.03 plasma.slim - In Dolphin's right-click context menu 'Share' option is missing

### ISSUE THREAD

**Issue by hakerdefo** [OpenMandrivaAssociation/distribution#2912]
**OpenMandriva version**: ROME 23.03 plasma.slim

In Dolphin, right-click on a file and `Share` is one of the options available but in ROME 23.03 plasma.slim this right-click context-menu item is missing. I'm not sure whether this behavior exists on the full plasma version r not but it definitely is an issue on the slim version. 

The issue is an easy fix. This is happening because ROME 23.03 plasma.slim edition doesn't come with a required package called `purpose`. Installing `purpose` fixes this issue and the right-click context-menu item `Share` is available. So, in the future versions of plasma.slim please include `purpose` by default.

**Comment by benbullard79** [comment]
Looks like `purpose` is installed by default on Rome Plasma. Perhaps esteemed developers need to make this a requires for Dolphin or a default packages for Rome slim versions.

**Comment by rugyada** [comment]
> I'm not sure whether this behavior exists on the full plasma version r not but it definitely is an issue on the slim version.

To be clear, I would not consider this a bug as in the slim ISO a lot of stuff is not installed **by design** and the right-click context-menu 'Share' is just a feature, which one may need or not.

![ss_20230508_013449](https://user-images.githubusercontent.com/46781309/236710013-e97b36a5-a33b-4eb5-8594-ce4fdd581a55.jpg)

The full featured Plasma ISO may fit better to someone's preferences, or others just agree with the Slim ISO concept and install only what they need.

Nevertheless, since it's matter of few  only a few kBs I add purpose to ISO packages list.

**Comment by hakerdefo** [comment]
@rugyada @benbullard79 :+1: 

Thanks for updating the ISO and adding the package `purpose` as the part of the default install. I wouldn't have raised the issue had it not been a difficult nut to crack. It took me quite a bit of digging-around to figure this out and in my humble opinion, it would have been near impossible for a new user to figure this out on his/her own.
