### ISSUE TITLE
Error: Unable to find a match: python3-dnf python3-dnf-plugins-core

### ISSUE THREAD

**Issue by denisgolius** [OpenMandrivaAssociation/distribution#2945]
**OpenMandriva version**:
`openmandriva-rolling-x86_64` from copr.fedorainfracloud.org

**Describe the bug**:
Build has been failed - see full log at https://download.copr.fedorainfracloud.org/results/victoriametrics/VictoriaMetrics-LTS/openmandriva-rolling-x86_64/06601796-vmsingle/builder-live.log.gz

```console
Copr repository                                  76 kB/s | 5.1 kB     00:00    
determining the fastest mirror (17 hosts).. done.
OpenMandriva Rolling - x86_64                   5.6 MB/s |  20 MB     00:03    
No match for argument: python3-dnf
No match for argument: python3-dnf-plugins-core
Error: Unable to find a match: python3-dnf python3-dnf-plugins-core
WARNING: DNF command failed, retrying, attempt #2, sleeping 10s
No matches found for the following disable plugin patterns: local, spacewalk, versionlock
Updating Subscription Management repositories.
Unable to read consumer identity
```

**Steps to reproduce**:

  1.  Add new release tag of VictoriaMetrics to https://github.com/VictoriaMetrics/victoriametrics-lts-rpm/blob/master/vmsingle.spec#L2 or to other spec files
  2. Wait while Fedora COPR finished build process
  3. See results at https://copr.fedorainfracloud.org/coprs/victoriametrics/VictoriaMetrics-LTS/builds/

**Observed behavior**:
Every build for OpenMandriva has been failed for the latest two month

**Expected behavior**:
Successful build. 

**Additional comment**:
It would be great if OpenMandriva maintainers will provide the same names for compatibility with other distributions. 

**Logs and screenshots if relevant**
See logs at https://download.copr.fedorainfracloud.org/results/victoriametrics/VictoriaMetrics-LTS/openmandriva-cooker-x86_64/06601796-vmsingle/builder-live.log.gz

I'v also opened the same issue on mock repository https://github.com/rpm-software-management/mock/issues/1251

**Comment by berolinux** [comment]
Thanks for the report.

There are reasons why we don't use the same package names -- we prefer keeping the package names unversioned (so e.g. `python-dnf` rather than `python3-dnf`) for the main version of the package.

The reason for this is that at some point, python 4 will come out -- once that's possible, we will build dnf with that. Using our package names, that will update cleanly (python is updated to 4.0, at the same time `python-dnf` is updated, removing the python3 version that is no longer needed).

Using the versioning scheme some other distributions are using, at that time we'd also have to rename `python3-dnf` to `python4-dnf`. This would still allow updating (python updated to 4.0, `python4-dnf` installed), but it would leave the old `python3-dnf` package installed, which is not what we'd usually want in this context. Of course we could add `Obsoletes: python3-dnf` to `python4-dnf` which would allow updating with removing the old package, but that would break explicitly installing a compat `python3-dnf` package for people who still need python 3.x for some reason.

This is why we use unversioned names for the main version of a package (`python-dnf`, `lib64ssl`, ...) and versioned names for compat packages only (`python2-dnf`, `lib64ssl1`, ...)

We could make your spec file happy by adding a `Provides: python3-XYZ = %{EVRD}` to all `python-XYZ` packages, but wouldn't it be better to pull the right packages in without insisting on a particular naming scheme?
At least as far as I know, all rpm based distributions these days have a virtual `python%{pyver}dist(xyz)` provide for `python[3]-xyz`, so it would probably be a better fix to change the hardcoded `BuildRequires: python3-dnf` to `BuildRequires: python%{pyver}dist(dnf)`.
That will work even if for some reason some other distribution names the package with yet another completely different naming scheme (e.g. `libdnf-python` or something).

Is there any reason not to fix it that way?

**Comment by benbullard79** [comment]
What are we trying to resolve here? When people report something like "xyz does not work" and it turns out they are trying to use packages names the OpenMandriva does not use I consider that

**Comment by denisgolius** [comment]
> What are we trying to resolve here? When people report something like "xyz does not work" and it turns out they are trying to use packages names the OpenMandriva does not use I consider that

Ok. So, it's better to drop OpenMandriva support in VictoriaMetrics rpm packages rather than resolve this issue with the OpenMandriva development team. Do I understand your point correctly?

**Comment by AngryPenguinPL** [comment]
> Ok. So, it's better to drop OpenMandriva support in VictoriaMetrics rpm packages rather than resolve this issue with the OpenMandriva development team. Do I understand your point correctly?
@denisgolius 

No, I think we've misunderstood a few things here.
We're glad you've decided to add support for OpenMandriva in VictoriaMetrics.
However, the problem you encountered seems to us to be an upstream mock problem and should be resolved there. Of course, we can introduce workaround by adding virtual provides to several packages - as @berolinux  wrote, but this may make several things more difficult in the future.

Fortunately, it seems that the upstream mock has already fixed the problem here https://github.com/rpm-software-management/mock/pull/1252 and as soon as the new version is released, compilation for OpenMandriva will be possible again.

Thank you for contacting us.
