### ISSUE TITLE
update problem persist

### ISSUE THREAD

**Issue by GhostPopular** [OpenMandrivaAssociation/distribution#3012]
Hi, I've tried to update my OS several times but I still have this problem. Thank you in advance for helping me and which command line, if necessary, would be best suited. Best regards. GP

<html>Erreur interne:<br/><br/>Error running transaction: libperl.so.5.38()(64bit) est nécessaire pour (déjà installé) perl-XML-Parser-2.47-1.x86_64</html>

My computer Operating System: OpenMandriva ROME 24.09
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.6.0
Qt Version: 6.7.2
Kernel Version: 6.10.1-desktop-1omv2490 (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® N100
Memory: 15.4 Gio of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: AZW
Product Name: MINI S

**Comment by benbullard79** [comment]
This is all the information you give us regarding the upgrade:

`Error running transaction: libperl.so.5.38()(64bit) est nécessaire pour (déjà installé) perl-XML-Parser-2.47-1.x86_64`

It is best to include all the output of your attempt to `dsync` or `upgrade` your system including the command used. The best command to update a OMLx system is actually several commands in sequence:

```
sudo dnf clean all
sudo dnf dsync
sudo dnf autoremove
```

OpenMandriva is admittedly and on purpose different from other distros. The way we package works better with `dnf dsync` rather than `dnf up`. 

_Tip_: Sometimes, for instance when some package undergoes a name change, it can be useful to use `sudo dnf  --allowerasing`. Just pay attention to what gets erased for obvious reasons, Same when you run `sudo dnf autoremove`. `autoremove` removes packages originally installed as dependencies that are no longer needed, but still pay attention to what gets removed.

_Another tip_: copy and paste this file:///usr/share/mdk/about/index.html in a browser and that should show a list of resources.

**Note**: `dnf dsync` is an alias for `dnf distro-sync`. `dnf up is an alias for `dnf upgrade`.

**Comment by benbullard79** [comment]
![Screenshot_20241205_101131](https://github.com/user-attachments/assets/62b745bb-1649-4459-8a03-87ee84f4e031)

`perl-XML-Parser` does install here in ROME P6 znver1 system. This suggests that `sudo dnf clean all` might allow `sudo dnf dsync` to proceed,

**Comment by GhostPopular** [comment]
Hi, thank you very much for your valuable help. Best regards
